### PR TITLE
Make syslog template configurable

### PR DESCRIPTION
**Pull request by elemoine**
This is an attempt to change the log format in the Rsyslog configuration. This is very WIP and untested at the moment.

### CODE REVIEW

**Comment by SwannCroiset** [comment]
Any reason to not use the rsyslog formula ? (although the rsyslog formula is not used anywhere I'd rather use it)
In an ideal world, the "Template Rfc3164Log" must be accessible to configure the heka logstreamer decoder

**Comment by elemoine** [comment]
> Any reason to not use the rsyslog formula ? (although the rsyslog formula is not used anywhere I'd rather use it)

I don't know. Last time I talked to @cznewt about this, I think he did not like the idea of having a formula just for Rsyslog.

One advantage of configuring Rsyslog in the Linux formula is that we reuse the template string for configuring the Heka syslog decoder.

> In an ideal world, the "Template Rfc3164Log" must be accessible to configure the heka logstreamer decoder

Yes, that was my plan. It's now implemented.

**Comment by elemoine** [comment]
I updated the branch and the commit message to describe what this PR provides. This is now ready for review.

**Comment by SwannCroiset** [comment]
Successfully tested, works for both trusty and xenial

**Comment by fpytloun** [comment]
I personally don't like abusing linux formula while there is already rsyslog formula for this purpose: https://github.com/tcpcloud/salt-formula-rsyslog
And is designed even for more advanced use-cases.

Ad. this change:
1. it's not possible to change template as it's only simple file.replace
2. I prefer approach like: "Don't do anything unless metadata define to do something" - after this change, rsyslog is automatically configured in some specific way which should not happen.

**Comment by elemoine** [comment]
> I personally don't like abusing linux formula while there is already rsyslog formula for this purpose: https://github.com/tcpcloud/salt-formula-rsyslog
> And is designed even for more advanced use-cases.

In the past @cznewt said that this formula was old, not used and probably broken.

> it's not possible to change template as it's only simple file.replace

What template are you talking about here?

You'd rather add a `rsyslog.conf` jinja template within the formula instead of "patching" the `rsyslog.conf` file provided by the rsyslog package. Am I understanding you correctly?




> I prefer approach like: "Don't do anything unless metadata define to do something" - after this change, rsyslog is automatically configured in some specific way which should not happen.

Yep, I can do that just by removing the changes to metadata/service/system/init.yml. That means the RFC3164 log format will be configured at the system class level (in the user model).

**Comment by fpytloun** [comment]
> In the past @cznewt said that this formula was old, not used and probably broken.
I didn't deny that.. :-) But it's probably best time to clean it up and start using it.

> You'd rather add a rsyslog.conf jinja template within the formula instead of "patching" the rsyslog.conf file provided by the rsyslog package. Am I understanding you correctly?
Yes, or maintain files in `/etc/rsyslog.d`.. but in both cases it may be worth separate formula.

> Yep, I can do that just by removing the changes to metadata/service/system/init.yml
That will still force rsyslog packages and service by default.

**Comment by elemoine** [comment]
We decided to try doing the work in the rsyslog formula, so I'm closing this for now.

**Pull request closed without merging**
